Do some code quality check and fix #126

diff --git a/bin/setup-runtime b/bin/setup-runtime
--- a/bin/setup-runtime
+++ b/bin/setup-runtime
@@ -22,7 +22,7 @@ esac
 
 # set project dir
 __DIR__=$(cd "$(dirname "$0")" && pwd)
-__PROJECT__=$(cd ${__DIR__}/../ && pwd)
+__PROJECT__=$(cd "${__DIR__}"/../ && pwd)
 
 # set download dir
 __PHP_RUNTIME_URL__="https://dl.zhamao.xin/static-php-cli/php-8.2.6-cli-${__OS_FIXED__}-${__ARCH__}.tar.gz"
@@ -52,17 +52,17 @@ china)
 
 esac
 
-test -d ${__PROJECT__}/downloads || mkdir ${__PROJECT__}/downloads
+test -d "${__PROJECT__}"/downloads || mkdir "${__PROJECT__}"/downloads
 # download static php binary
-test -f ${__PROJECT__}/downloads/runtime.tar.gz || { echo "Downloading $__PHP_RUNTIME_URL__ ..." && curl -#fSL -o ${__PROJECT__}/downloads/runtime.tar.gz "$__PHP_RUNTIME_URL__" ; }
-test -f ${__DIR__}/php || { tar -xf ${__PROJECT__}/downloads/runtime.tar.gz -C ${__DIR__}/ ; }
-chmod +x ${__DIR__}/php
+test -f "${__PROJECT__}"/downloads/runtime.tar.gz || { echo "Downloading $__PHP_RUNTIME_URL__ ..." && curl -#fSL -o "${__PROJECT__}"/downloads/runtime.tar.gz "$__PHP_RUNTIME_URL__" ; }
+test -f "${__DIR__}"/php || { tar -xf "${__PROJECT__}"/downloads/runtime.tar.gz -C "${__DIR__}"/ ; }
+chmod +x "${__DIR__}"/php
 # download composer
-test -f ${__DIR__}/composer || curl -#fSL -o ${__DIR__}/composer "$__COMPOSER_URL__"
-chmod +x ${__DIR__}/composer
+test -f "${__DIR__}"/composer || curl -#fSL -o "${__DIR__}"/composer "$__COMPOSER_URL__"
+chmod +x "${__DIR__}"/composer
 # sanity check for php and composer
-${__DIR__}/php -v >/dev/null || { echo "Failed to run php" && exit 1; }
-${__DIR__}/php ${__DIR__}/composer --version >/dev/null || { echo "Failed to run composer" && exit 1; }
+"${__DIR__}"/php -v >/dev/null || { echo "Failed to run php" && exit 1; }
+"${__DIR__}"/php "${__DIR__}"/composer --version >/dev/null || { echo "Failed to run composer" && exit 1; }
 
 echo "Setup runtime OK!"
 echo "runtime bin path needs to add manually by command below:"
